baseURL = "https://bfdball.firecat53.com"
languageCode = "en-us"
title = "Bellingham Firefighters Community Ball"
theme = "ananke"

[params]
    background_color_class = "bg-red"
    featured_image = false
    facebook = "https://www.facebook.com/iaff106/"
    custom_css = ["static.css"]
